#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --gres=gpu
#SBATCH -p ug-gpu-small
#SBATCH --qos=short
#SBATCH --job-name=dcganPegasus
#SBATCH -o ./dcganOutput.txt

source /etc/profile
module load cuda/10.1

python3 ./dcgan.py
